spring-boot-plus:
  # 是否启用ansi控制台输出有颜色的字体，local环境建议开启，服务器环境设置为false
  enable-ansi: true

server:
  port: 4397
  servlet:
    context-path: /
spring:
  datasource:
    dynamic:
      primary: application
      datasource:
        permission:
          username: PumpDD_Wavenet
            password: Wavenet_PumpDD2020
            driver-class-name: oracle.jdbc.driver.OracleDriver
            url: jdbc:oracle:thin:@//31.16.27.16:1521/pstest

#          username: wavenet
#          password: wangbo_2019
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://47.100.60.161:3306/spring-boot?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
#        application:
#          username: YP_GDYHJGPT
#          password: YP_GDYHJGPT
#          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#          url: jdbc:sqlserver://172.18.1.128;Databasename=YP_GDYHJGPT

  # Redis配置
#  redis:
#    database: 0
#    host: 47.100.60.161
#    password:
#    port: 6379

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
